# -*- coding: utf-8 -*-
"""
council_report.py
All output data structures for the Council of Experts.

Hierarchy:
    CouncilReport
    ├── expert_reports      Three raw reports (preserved as-is)
    ├── critiques           Six directional CritiqueResults
    ├── council_decision    Arbitration output (pure code, no LLM)
    └── metadata
"""

from dataclasses import dataclass, field
from typing import Optional
import json


# ── Critique structures ────────────────────────────────────────────────────────

@dataclass
class CritiqueContext:
    """
    Structured summary passed to the Critique LLM.
    Mapped from raw Expert reports into a unified format.
    """
    expert:         str            # e.g. "security_adversarial"
    recommendation: str            # APPROVE / REVIEW / REJECT
    scores: dict = field(default_factory=dict)
    # {
    #   "privacy":      int,   # 1-5
    #   "transparency": int,
    #   "bias":         int,
    # }

    key_findings: list = field(default_factory=list)
    # [{"finding": str, "type": str, "urgency": str}]
    # type: "technical_vulnerability" / "compliance_gap" / "un_principle_violation"

    unique_findings: list = field(default_factory=list)
    # Findings from dimensions only this Expert can assess
    # [{"finding": str, "type": "exclusive_dimension", "urgency": str}]

    note: str = ""
    # Raw text from council_handoff.note

    def to_prompt_str(self) -> str:
        """Format as a readable summary for the Critique prompt."""
        lines = [
            f"Expert role: {self.expert}",
            f"Assessment conclusion: {self.recommendation}",
            f"Core scores: privacy={self.scores.get('privacy', 'N/A')} "
            f"transparency={self.scores.get('transparency', 'N/A')} "
            f"bias={self.scores.get('bias', 'N/A')}",
        ]
        if self.key_findings:
            lines.append("Key findings:")
            for f in self.key_findings:
                lines.append(
                    f"  [{f.get('type', '')}][{f.get('urgency', '')}] "
                    f"{f.get('finding', '')}"
                )
        if self.unique_findings:
            lines.append("Exclusive dimension findings (not covered by other Experts):")
            for f in self.unique_findings:
                lines.append(f"  [{f.get('urgency', '')}] {f.get('finding', '')}")
        if self.note:
            lines.append(f"Note: {self.note}")
        return "\n".join(lines)


@dataclass
class CritiqueResult:
    """
    Output from one directional Critique.
    Example: Expert 1 critiquing Expert 2.
    """
    from_expert:         str    # Who wrote this critique
    on_expert:           str    # Who is being critiqued
    agrees:              bool   # Whether this Expert broadly agrees with the other
    key_point:           str    # Core observation from this Expert's professional lens
    new_information:     str    # What the other Expert found that this framework missed
    stance:              str    # "maintain original assessment" or similar
    evidence_references: list = field(default_factory=list)
    # Pointers to specific fields in the other Expert's report, e.g.:
    # ["Expert2.regulatory_citations: GDPR Art.32"]

    def to_dict(self) -> dict:
        return {
            "from_expert":         self.from_expert,
            "on_expert":           self.on_expert,
            "agrees":              self.agrees,
            "key_point":           self.key_point,
            "new_information":     self.new_information,
            "stance":              self.stance,
            "evidence_references": self.evidence_references,
        }


# ── Disagreement structures ────────────────────────────────────────────────────

@dataclass
class Disagreement:
    """
    A recorded disagreement between two or more Experts.
    Detected by the arbitration layer (pure code), not generated by LLM.
    """
    dimension:         str    # e.g. "privacy"
    values:            dict   # {"security": 4, "governance": 1, "un_mission_fit": 4}
    type:              str    # "test_pass_doc_fail" / "test_fail_doc_pass" / "framework_difference"
    description:       str    # Human-readable disagreement description
    escalate_to_human: bool = False  # Whether mandatory human review is required

    def to_dict(self) -> dict:
        return {
            "dimension":          self.dimension,
            "values":             self.values,
            "type":               self.type,
            "description":        self.description,
            "escalate_to_human":  self.escalate_to_human,
        }


# ── Arbitration decision ───────────────────────────────────────────────────────

@dataclass
class CouncilDecision:
    """
    Final decision from the arbitration layer.
    All fields computed by pure code rules — no LLM involvement.
    """
    final_recommendation:         str    # APPROVE / REVIEW / REJECT (most conservative)
    consensus_level:              str    # FULL / PARTIAL / SPLIT
    human_oversight_required:     bool   # True if any Expert requires it
    compliance_blocks_deployment: bool   # True if any Expert blocks deployment

    agreements:    list = field(default_factory=list)
    # Dimensions where all three Experts agree, e.g. ["bias_fairness"]

    disagreements: list = field(default_factory=list)
    # List[Disagreement]

    rationale:     str = ""
    # Template-generated decision rationale (not LLM-generated)

    def to_dict(self) -> dict:
        return {
            "final_recommendation":         self.final_recommendation,
            "consensus_level":              self.consensus_level,
            "human_oversight_required":     self.human_oversight_required,
            "compliance_blocks_deployment": self.compliance_blocks_deployment,
            "agreements":                   self.agreements,
            "disagreements": [
                d.to_dict() if isinstance(d, Disagreement) else d
                for d in self.disagreements
            ],
            "rationale": self.rationale,
        }


# ── Final report ───────────────────────────────────────────────────────────────

@dataclass
class CouncilReport:
    """
    Complete output from the Council of Experts.

    Structure:
        metadata         - agent_id / timestamp / session_id
        expert_reports   - Three raw reports, preserved as-is
        critiques        - Six directional CritiqueResults
        council_decision - Arbitration output (pure code)
    """
    # Metadata
    agent_id:   str
    session_id: str
    timestamp:  str

    # Three raw Expert reports (dict, preserved as-is, no modification)
    expert_reports: dict = field(default_factory=dict)
    # {
    #   "security":       Expert1Report dict,
    #   "governance":     Expert2Report dict,
    #   "un_mission_fit": Expert3Report dict,
    # }

    # Six directional Critiques
    critiques: dict = field(default_factory=dict)
    # {
    #   "security_on_governance":          CritiqueResult,
    #   "security_on_un_mission_fit":      CritiqueResult,
    #   "governance_on_security":          CritiqueResult,
    #   "governance_on_un_mission_fit":    CritiqueResult,
    #   "un_mission_fit_on_security":      CritiqueResult,
    #   "un_mission_fit_on_governance":    CritiqueResult,
    # }

    # Arbitration decision
    council_decision: Optional[CouncilDecision] = None

    # Summary note for human reviewers (template-generated, not LLM)
    council_note: str = ""

    def to_dict(self) -> dict:
        return {
            "agent_id":   self.agent_id,
            "session_id": self.session_id,
            "timestamp":  self.timestamp,
            "expert_reports": self.expert_reports,
            "critiques": {
                k: v.to_dict() if isinstance(v, CritiqueResult) else v
                for k, v in self.critiques.items()
            },
            "council_decision": (
                self.council_decision.to_dict()
                if self.council_decision else None
            ),
            "council_note": self.council_note,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=indent)
