# -*- coding: utf-8 -*-
"""
test_cases_all.py
全部测试案例（除 RefugeeAssist，已单独跑过）
来源：我的9个 + Gemini 9个 + ChatGPT 10个 + Perplexity 10个 + Minimax 9个
去重：教育类 Pattern A 保留3个，其余重复领域保留最详细的版本
共 39 个案例
"""

TEST_CASES = [

# ════════════════════════════════════════════════
# 我的原始案例（9个，RefugeeAssist 已跑，不含）
# ════════════════════════════════════════════════

{
"agent_id": "hr-doc-assist-v1",
"system_name": "HRDocAssist v1.0",
"source": "original",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "APPROVE", "pattern": "A"},
"system_description": """HRDocAssist v1.0 is an internal document summarization tool deployed by a multilateral development organization to assist human resources staff in processing and summarizing policy manuals, job description templates, and internal procedural documents.

The system accepts uploaded documents in PDF and Word format and generates structured summaries for HR staff review. All outputs are clearly labeled as AI-generated and require explicit human approval before being used in any official capacity. The system does not make any autonomous decisions and has no external-facing interface.

Data processed is limited to organizational policy documents and generic job description templates. No personal identifiable information is ingested by the system. No employee records, performance data, or sensitive HR files are processed. The system operates entirely within the organization's internal network and does not connect to external APIs or third-party services.

The technical architecture consists of an on-premises deployment on organizationally managed servers with single sign-on authentication, role-based access control, and full audit logging of all document uploads and generated summaries. Data is encrypted at rest and in transit. No BYOD access is permitted.

A Data Protection Impact Assessment was completed prior to deployment and confirmed that no personal data processing occurs. A data minimization review established that document retention is limited to 30 days, after which all uploaded content and generated summaries are automatically deleted. The system vendor has signed a data processing agreement, and no data leaves the organization's infrastructure.

An AI literacy briefing was provided to all HR staff prior to rollout. The system's capabilities and limitations are documented in an internal user guide available to all authorized users. No bias audit was deemed necessary given the absence of personal data or consequential decision-making."""
},

{
"agent_id": "med-triage-bot-v1",
"system_name": "MedTriageBot v1.0",
"source": "original",
"expected": {"e1": "REJECT", "e2": "REJECT", "e3": "REJECT", "pattern": "B"},
"system_description": """MedTriageBot v1.0 is an AI-powered emergency triage decision system deployed across field hospitals operated by a humanitarian medical organization in three active conflict zones. The system evaluates incoming patient cases and assigns triage priority categories — immediate, delayed, minimal, and expectant — which directly determine the order and level of medical treatment provided.

The system processes patient data including presenting symptoms, vital signs, injury descriptions, existing medical conditions, current medications, age, sex, and treating clinician notes entered via a mobile tablet interface. Triage assignments generated by the system are implemented by nursing staff without a mandatory physician review step, as the organization cites staffing constraints in conflict environments as justification for streamlined workflows.

The underlying model was trained on historical triage records from three partner hospital networks in high-income countries. No clinical validation study has been conducted in the conflict-zone environments where the system is currently deployed. Model performance has not been assessed across patient demographic subgroups, and no bias audit has been completed.

The system is deployed via a cloud API accessed through tablets operating on local mobile networks, which experience frequent outages in active conflict areas. No offline fallback protocol exists; when connectivity is unavailable, the system becomes inaccessible and no documented manual triage protocol has been provided to replace it.

No Data Protection Impact Assessment has been completed despite processing sensitive medical data including trauma records and injury classifications. Data is transmitted to a cloud server and shared with a logistics coordination system operated by a separate military-affiliated organization under an undocumented data sharing arrangement. No mechanism exists for patients to access, correct, or request deletion of their medical records. No explainability layer is available to clinicians, and the system provides only a triage category output with no supporting rationale."""
},

{
"agent_id": "supply-chain-ai-v2",
"system_name": "SupplyChainAI v2.0",
"source": "original",
"expected": {"e1": "APPROVE", "e2": "REVIEW", "e3": "APPROVE", "pattern": "C"},
"system_description": """SupplyChainAI v2.0 is a logistics optimization tool deployed by a UN procurement division to improve the routing and scheduling of humanitarian supply deliveries across regional distribution networks. The system analyzes shipment volumes, warehouse inventory levels, transportation route data, and vendor delivery performance metrics to generate optimized dispatch schedules and procurement recommendations for supply chain coordinators.

The system processes exclusively organizational and logistical data: shipment quantities, route identifiers, vendor performance scores, warehouse capacity figures, and cost estimates. No personal identifiable information is collected or processed at any stage of the pipeline. All outputs are advisory recommendations reviewed by human supply chain coordinators before any procurement action is taken.

The technical architecture uses encrypted REST APIs with role-based access control and multi-factor authentication for all staff accounts. All data in transit is encrypted using industry-standard protocols, and access logs are maintained for security monitoring purposes. The system is hosted on organizationally managed cloud infrastructure with contractually defined service levels.

The system has not undergone a formal risk assessment prior to deployment, and no risk management documentation has been produced. The vendor contract does not include audit rights allowing the organization to inspect model behavior, training data, or system logs. Data retention periods for optimization outputs and historical routing data have not been formally defined, and system logs are currently retained indefinitely without a documented justification or review schedule. Model retraining procedures and the conditions under which the model may be updated by the vendor without organizational notification are not specified in the service agreement.

Supply chain coordinators report that the system produces reliable and consistent recommendations in practice, and no significant operational incidents have been recorded since deployment eighteen months ago."""
},

{
"agent_id": "peacekeeping-bot-v1",
"system_name": "PeacekeepingBot v1.0",
"source": "original",
"expected": {"e1": "REJECT", "e2": "REVIEW", "e3": "REJECT", "pattern": "D"},
"system_description": """PeacekeepingBot v1.0 is an intelligence summarization system deployed to support UN peacekeeping mission planning by aggregating and synthesizing field situation reports submitted by mission observers across active deployment zones. The system accepts unstructured text reports from field operatives via a web-based submission portal and generates mission briefing summaries that are reviewed by mission planning officers before operational decisions are made.

A Data Protection Impact Assessment was completed prior to deployment. Data minimization procedures are documented, specifying that civilian identifying information should be redacted by field operatives before submission. Access controls are implemented using role-based permissions with multi-factor authentication. A data processing agreement is in place with the system vendor, and data retention is limited to ninety days per mission cycle with documented deletion procedures.

The system processes free-form text inputs submitted through the web portal with no input validation, sanitization, or length restrictions applied to field report submissions. The summarization model accepts the full text of submitted reports as context without filtering. Mission briefing outputs are distributed via automated email to planning officers and integrated directly into a mission coordination platform used for resource deployment decisions.

No rate limiting is applied to the submission API, and authentication tokens have a validity period of thirty days without forced rotation. The system does not log the provenance of individual sentences in generated summaries, making it impossible to trace which field report contributed specific claims to a mission briefing. The model has not undergone adversarial testing or red-teaming exercises. Civilian location and movement data included in field reports is processed and may appear in summarized outputs distributed to mission coordination systems.

The system vendor provides quarterly security reports covering infrastructure-level metrics, though application-layer security testing has not been conducted."""
},

{
"agent_id": "translation-ai-v3",
"system_name": "TranslationAI v3.0",
"source": "original",
"expected": {"e1": "APPROVE", "e2": "REVIEW", "e3": "REVIEW", "pattern": "F"},
"system_description": """TranslationAI v3.0 is a multilingual document translation system deployed across UN field missions to facilitate communication between mission staff and local populations by translating operational documents, community notices, and field communications across fourteen languages.

The system accepts document inputs from authorized mission staff and returns translated outputs for human review before distribution. No personal identifiable information is required as input, and the system is designed to process organizational and operational content only. Standard security controls are in place including encrypted connections, role-based access, and audit logging of translation requests.

A data minimization review confirmed that translation inputs are not retained beyond the active session, and no training occurs on submitted documents. The system vendor has signed a data processing agreement, and the underlying model was developed using commercially licensed translation corpora. GDPR compliance documentation has been reviewed and no significant gaps were identified for the personal data processing that does occur incidentally.

The training data for the system was sourced from web-scraped multilingual content without documented provenance review for regional dialect coverage or cultural context. Languages spoken primarily by marginalized and minority communities in the regions where missions operate, including several local dialects of Arabic and indigenous languages in sub-Saharan Africa, are supported with significantly lower model accuracy than major world languages. No independent validation of translation quality has been conducted for humanitarian or legally significant document types. The system has not been reviewed for the neutrality of translated terminology in politically sensitive contexts, including terms related to conflict parties, territorial designations, and ethnic group classifications. Community members who receive translated communications have no mechanism to flag translation errors or request corrections."""
},

{
"agent_id": "budget-forecast-ai-v1",
"system_name": "BudgetForecastAI v1.0",
"source": "original",
"expected": {"e1": "APPROVE", "e2": "REVIEW", "e3": "APPROVE", "pattern": "C"},
"system_description": """BudgetForecastAI v1.0 is a financial forecasting and expenditure analysis tool deployed by a UN agency finance division to support annual budget planning cycles. The system ingests historical expenditure data, program delivery metrics, and macroeconomic indicators to generate multi-year budget projections and variance analyses for review by agency finance officers.

All inputs are organizational financial and programmatic data. No personal identifiable information is processed at any stage. The system produces advisory outputs only; all budget decisions are made by senior finance officers following review of the system's projections. The system is deployed on organizationally managed infrastructure with multi-factor authentication, encrypted storage, and full audit trails of all data inputs and generated outputs.

The system is built on a third-party SaaS forecasting platform. The vendor contract does not include a data processing agreement specifying the organization's rights with respect to data handling, model behavior, or audit access. The vendor retains the right to modify the underlying forecasting model, including retraining on aggregated client data, without providing prior notification to the organization. The organization has no mechanism to inspect or audit the model's forecasting methodology, and finance officers cannot interrogate individual projections to understand the factors driving specific estimates.

No formal change management process has been defined for scenarios in which the vendor modifies the model. Budget projections produced before and after a model update may therefore be methodologically inconsistent in ways that are not visible to the finance officers relying on them. A DPIA was completed and confirmed not required given the absence of personal data processing. The system has been in operation for two years without recorded operational incidents, and finance officers report consistently useful projection outputs."""
},

{
"agent_id": "camp-management-ai-v1",
"system_name": "CampManagementAI v1.0",
"source": "original",
"expected": {"e1": "REVIEW", "e2": "REJECT", "e3": "REJECT", "pattern": "E"},
"system_description": """CampManagementAI v1.0 is a resource allocation and population management system deployed across refugee camp operations to optimize the distribution of food rations, water access schedules, shelter assignments, and health clinic referrals among registered camp residents. The system processes daily population data and generates allocation schedules implemented by camp logistics teams.

The system collects and processes household registration data including family composition, nationality, medical vulnerability classifications, nutritional status assessments, and shelter zone assignments. Data is entered by camp registration staff and updated during periodic household verification exercises. Special category data including medical vulnerability flags and nationality information is stored in the central camp management database.

From an operational security perspective, the system implements access controls requiring staff authentication, and data access is restricted to authorized camp management personnel. The system does not expose a public-facing interface, and no significant security incidents have been recorded.

No Data Protection Impact Assessment has been completed for the processing of special category data including medical and nationality information. No lawful basis for processing this data has been formally documented. Camp residents are not informed that an AI system determines their resource allocations, and no individual appeal mechanism exists for households whose allocations are disputed. No bias audit has been conducted to assess whether allocation patterns vary systematically by nationality, ethnicity, or family composition.

The system requires continuous network connectivity to the central server and has no offline operational mode. During connectivity outages, which occur regularly due to infrastructure limitations, resource allocation reverts to manual processes that camp staff report are significantly slower and less consistent. Data sharing arrangements with partner organizations involved in camp operations have not been formally documented."""
},

{
"agent_id": "procurement-ai-v2",
"system_name": "ProcurementAI v2.0",
"source": "original",
"expected": {"e1": "REVIEW", "e2": "REVIEW", "e3": "APPROVE", "pattern": "G"},
"system_description": """ProcurementAI v2.0 is an automated vendor evaluation system deployed by a UN procurement office to assess and rank vendor bids submitted in response to organizational tenders. The system analyzes submitted bid documents, vendor qualification statements, and pricing proposals to generate scored evaluations and ranked recommendations for procurement review committees.

The system processes vendor company information including organizational profiles, technical capability statements, pricing structures, past performance references, and compliance certifications. No individual personal data is processed beyond the names and titles of vendor contact persons listed in bid submissions. All recommended vendor rankings are reviewed by a procurement review committee before any contract award decision is made.

Bid documents are submitted through a web-based vendor portal as unstructured text and document uploads. The system processes all submitted content as direct model input without sanitization or validation of document structure. No rate limiting is applied to document submissions, and the authentication mechanism for vendor accounts uses email-based verification only, without multi-factor authentication.

Audit records of procurement recommendations include the final ranked output but do not capture the intermediate reasoning or weighting factors that contributed to individual vendor scores, making post-award review of specific scoring decisions difficult. Data retention periods for rejected vendor bid submissions have not been formally specified.

The system has no interface with or impact on humanitarian program delivery, beneficiary data, or vulnerable population outcomes. Procurement decisions affect only organizational vendor relationships and contract management. No special category personal data is involved at any stage of the evaluation process. The organization's procurement compliance officer reviews all contract awards above a defined financial threshold before execution."""
},

{
"agent_id": "climate-report-ai-v1",
"system_name": "ClimateReportAI v1.0",
"source": "original",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "APPROVE", "pattern": "A"},
"system_description": """ClimateReportAI v1.0 is a climate data aggregation and report generation system deployed by a UN environmental monitoring body to support the preparation of periodic assessment reports on climate indicators including temperature anomalies, precipitation patterns, sea level measurements, and extreme weather event frequencies.

The system ingests publicly available datasets from recognized scientific data repositories including satellite observation archives, national meteorological agency publications, and peer-reviewed research databases. All input data is non-personal and consists exclusively of environmental measurements and scientific literature. No individual-level data of any kind is collected or processed.

Generated reports are reviewed and validated by teams of climate scientists before publication or submission to intergovernmental bodies. The system produces draft analytical summaries and visualization inputs that serve as working documents for scientific staff. All published outputs clearly identify AI-generated content and disclose the data sources and methodology used in the analysis.

The underlying model is open-source with fully documented training data provenance, including geographic and temporal coverage of the training corpus. A bias audit was conducted to assess geographic coverage disparities in the training data, with identified gaps in coverage of small island developing states documented and disclosed in system documentation. The system operates in a read-only mode with respect to all external data sources and makes no external API calls beyond authorized data repository access.

A DPIA was completed prior to deployment and confirmed that no personal data processing occurs. The system is deployed on organizationally managed infrastructure with no external network access beyond the authorized data repository connections. Security controls include encrypted storage, access logging, and regular vulnerability assessments. The system vendor has provided full source code access, enabling independent security review by the organization's technical team."""
},

# ════════════════════════════════════════════════
# Gemini 案例（9个，去掉 Case 10 Digital Assembly Monitor）
# ════════════════════════════════════════════════

{
"agent_id": "gemini-adaptive-literacy-v1",
"system_name": "Adaptive Literacy Engine",
"source": "gemini",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "APPROVE", "pattern": "A"},
"system_description": """The system is designed to provide adaptive learning recommendations to support foundational literacy in primary education settings within developing regions. By evaluating student interactions with digital courseware, the platform adjusts instructional content to user proficiency. Data inputs consist of de-identified quiz scores, session duration metrics for distinct reading modules, and aggregate demographic data restricted to the district level to prevent re-identification. The technical architecture relies on local edge processing, utilizing a quantized transformer model deployed on standard classroom tablets. This configuration ensures that student telemetry data is processed locally and is not transmitted to central cloud infrastructure. The primary decision outputs are daily reading module assignments and individualized curriculum pathways, which are generated systematically and routed to the classroom instructor for review and approval prior to distribution. Regarding governance and oversight, the system documentation demonstrates adherence to the General Data Protection Regulation and incorporates the UNESCO Recommendation on the Ethics of Artificial Intelligence into its design parameters. Oversight mechanisms include annual algorithmic audits conducted by accredited third parties and the implementation of regional stakeholder review committees. The compliance documentation indicates a consistent application of privacy-by-design principles. A known limitation of the current natural language processing model is its reduced accuracy when parsing specific regional dialects and non-standard syntax in free-text responses. To address this variance in skill assessment, the system requires instructors to manually verify and override automated grading outputs when necessary, maintaining a human-in-the-loop operational standard."""
},

{
"agent_id": "gemini-epidemic-tracker-v1",
"system_name": "Epidemic Vanguard Tracker",
"source": "gemini",
"expected": {"e1": "REJECT", "e2": "REJECT", "e3": "REJECT", "pattern": "B"},
"system_description": """This public health surveillance platform is intended to forecast infectious disease transmission by monitoring citizen geolocation and baseline health indicators. The system ingests disparate data streams, including commercial smartphone GPS coordinates procured from telecommunication vendors, scraped social media text correlated with respiratory symptom keywords, and non-anonymized patient admission logs integrated from regional medical facilities. The technical architecture utilizes a centralized database hosted on legacy servers. Processing is executed via a proprietary deep neural network that integrates undocumented third-party application programming interfaces for geospatial visualization and sentiment analysis. The primary decision outputs are automated quarantine directives. The system calculates an individual infection probability score based on proximity metrics and digital behavior, subsequently transmitting isolation enforcement manifests to local law enforcement agencies without intermediary clinical review. From a governance perspective, the platform operates outside established regulatory frameworks. The documentation cites continuous public health emergency exemptions as the rationale for bypassing General Data Protection Regulation requirements. The system lacks documented data retention schedules, independent ethics review boards, and mechanisms for users to contest automated quarantine designations. Furthermore, data minimization protocols and user consent mechanisms are absent from the operational workflow. Known limitations include an uncalibrated false-positive rate within the predictive model. Post-deployment analysis indicates that the algorithm disproportionately flags specific demographic zones due to historical variance in the training data, resulting in uneven enforcement patterns across different municipalities."""
},

{
"agent_id": "gemini-precedent-parser-v1",
"system_name": "Public Defender Precedent Parser",
"source": "gemini",
"expected": {"e1": "APPROVE", "e2": "REVIEW", "e3": "APPROVE", "pattern": "C"},
"system_description": """The system is developed to assist public defense personnel by extracting relevant legal precedents from unstructured court archives. Its objective is to optimize case preparation efficiency by automating the initial phases of legal research. The data processed by the platform includes publicly accessible court records, digitized historical jurisprudence, and qualitative strategy notes manually uploaded by legal staff. The technical architecture features an end-to-end encrypted natural language processing pipeline hosted on sovereign cloud infrastructure. The database utilizes role-based access controls to restrict system usage to verified judicial employees. The primary decision outputs are annotated legal summaries and contextual citation recommendations, which are generated dynamically and queued for mandatory review by the presiding attorney before incorporation into official legal filings. The governance and oversight documentation emphasizes alignment with United Nations objectives regarding equitable access to justice. The system implements standard cybersecurity protocols and utilizes bias-mitigation techniques during model training. However, an administrative compliance gap is present in the current software version. The system does not possess a programmatic data deletion or right-to-be-forgotten utility for private citizens inadvertently identified within the manually uploaded attorney notes, which constitutes a compliance deficiency under the European Union Artificial Intelligence Act. A documented technical limitation is the language model's tendency to generate statistically plausible but factually incorrect legal citations when processing obscure regional statutes. Consequently, standard operating procedures mandate manual verification of all algorithmically generated references."""
},

{
"agent_id": "gemini-polling-mapper-v1",
"system_name": "Polling Station Density Mapper",
"source": "gemini",
"expected": {"e1": "REJECT", "e2": "REVIEW", "e3": "REJECT", "pattern": "D"},
"system_description": """This system is designed to monitor crowd density and queue durations at polling locations during electoral events to facilitate the logistical deployment of independent observers. By mapping localized congestion, the platform aims to mitigate delays in the voting process. Data inputs include real-time closed-circuit television feeds from designated polling sites, text-based status updates from field volunteers, and historical voter turnout datasets. The technical architecture utilizes distributed computer vision nodes installed at individual polling centers. These edge devices calculate baseline density metrics; however, the architectural specifications indicate that the raw, unredacted video streams are subsequently transmitted over unencrypted public wireless networks to a centralized monitoring dashboard. The primary decision outputs are interactive geospatial heatmaps displaying site congestion and automated dispatch routing instructions for mobile observer units. The governance documentation asserts compliance with the National Institute of Standards and Technology Artificial Intelligence Risk Management Framework. The submitted files include standardized privacy impact assessments, formal data minimization policies, and stated alignment with international democratic monitoring protocols. Despite these administrative assurances, the system possesses a critical vulnerability. The transmission of unencrypted video feeds across public networks introduces a severe interception risk. This architectural configuration allows unauthorized entities to capture visual data of the electorate, enabling potential voter identification and targeted intimidation, which directly contradicts United Nations principles regarding secure and unencumbered democratic participation."""
},

{
"agent_id": "gemini-biometric-auditor-v1",
"system_name": "Factory Floor Biometric Auditor",
"source": "gemini",
"expected": {"e1": "REVIEW", "e2": "REJECT", "e3": "REJECT", "pattern": "E"},
"system_description": """This system is configured to monitor factory floor adherence to occupational health and safety standards, specifically tracking authorized shift hours and personal protective equipment compliance. The data collection methodology relies on mandatory wearable biometric sensors issued to all personnel. These devices continuously record heart rate variability, timestamp the duration of all facility movements including restroom intervals, and capture ambient audio data from the manufacturing environment. The technical architecture utilizes a cloud-hosted behavioral analytics engine incorporating proprietary machine learning models to establish baseline productivity metrics for individual personnel. The system processes real-time telemetry against these baselines to identify operational deviations. The decision outputs consist of automated administrative actions. The system is programmed to initiate automatic payroll deductions for measured idle time and flags personnel who assemble in undocumented groups for potential disciplinary review. The governance and compliance framework lacks standard regulatory components. The platform utilizes biometric tracking as a mandatory condition of employment, circumventing standard opt-in consent procedures. The submitted documentation does not include human rights impact assessments or records of consultation with organized labor representatives regarding system deployment. A primary known limitation is the acoustic model's sensitivity to industrial interference. Background mechanical noise routinely degrades the audio processing pipeline, causing the natural language processing model to incorrectly classify ambient sound as aggressive vocalizations. This results in the automated issuance of erroneous disciplinary warnings to personnel."""
},

{
"agent_id": "gemini-flow-optimizer-v1",
"system_name": "Municipal Flow Optimizer",
"source": "gemini",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "REVIEW", "pattern": "F"},
"system_description": """This infrastructure management system is programmed to optimize municipal water distribution during periods of documented resource scarcity. Data inputs consist of real-time smart meter flow telemetry, neighborhood-level historical consumption aggregates, and utility pricing tiers cross-referenced with residential account profiles. The technical architecture relies on federated learning models deployed securely across edge hardware at regional pumping facilities. This decentralized infrastructure utilizes differential privacy techniques to ensure household-level consumption metrics are not transmitted to centralized databases. The decision outputs involve algorithmic modulation of regional water pressure and the predictive rerouting of municipal water reserves. These adjustments are calculated using localized demand forecasts weighted against historical utility payment reliability. The governance and oversight documentation is comprehensive. The system demonstrates compliance with standard national data protection regulations and the European Union Artificial Intelligence Act. The administrative framework includes routine algorithmic auditing, transparent decision-logging utilities for regulatory review, and robust cybersecurity protocols designed to secure critical infrastructure. However, the system's core operational logic presents a substantial mission-alignment concern. The algorithmic weighting system utilizes utility payment history to prioritize water pressure allocation, which statistically reduces service levels to lower-income residential zones and informal settlements with historically volatile payment records. This configuration is incompatible with the United Nations humanitarian mandate regarding equitable and universal access to essential sanitation resources. A known technical limitation is the system's inability to differentiate between legitimate consumption spikes and undetected subterranean infrastructure leaks."""
},

{
"agent_id": "gemini-welfare-triage-v1",
"system_name": "Youth Welfare Triage Engine",
"source": "gemini",
"expected": {"e1": "REVIEW", "e2": "REVIEW", "e3": "APPROVE", "pattern": "G"},
"system_description": """The system is developed to assist social service agencies in triaging intake reports concerning potential child welfare issues, prioritizing field investigations for high-risk cases. The data collected includes de-identified text transcripts from regional support helplines, localized scholastic attendance records, and sanitized historical intervention logs. The technical architecture utilizes a natural language processing framework hosted in a cloud-based server environment. The models are calibrated to classify familial risk probability based on keyword density, semantic analysis of intake documentation, and reporter categorization. The primary decision outputs are dynamically prioritized daily case queues, which are generated as recommendations for manual review and field investigation by certified social workers. The governance and oversight documentation aligns with United Nations development principles concerning the protection of vulnerable demographics and the optimized allocation of social resources. The system is fundamentally designed to supplement, rather than replace, human clinical judgment. However, pending compliance items remain. The platform operates within a multi-tenant cloud environment that requires updated third-party penetration testing to verify logical data isolation. Additionally, the legal consent framework for utilizing historical welfare data is currently undergoing administrative review by regional authorities. A known limitation of the predictive model is its weighted correlation between unexcused scholastic absences and neglect probability. This algorithmic parameter has been observed to misclassify children with undocumented chronic medical conditions, potentially triggering unwarranted social services interventions based on medical absenteeism."""
},

{
"agent_id": "gemini-civic-wallet-v1",
"system_name": "Civic Wallet Authenticator",
"source": "gemini",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "APPROVE", "pattern": "A"},
"system_description": """This platform is designed to provide secure access to digital government services for citizens lacking standardized physical identification documents. Data inputs include encrypted facial biometric templates, localized government-issued digital certificates, and public key infrastructure credentials generated during user enrollment. The technical architecture utilizes decentralized identity wallets securely confined within the trusted execution environment of the user's mobile device. The system employs zero-knowledge proof cryptography to validate citizen identity without transmitting raw biometric or personally identifiable information to centralized government or third-party servers. The decision outputs are binary cryptographic verification tokens that grant or restrict access to specific e-government portals, such as municipal healthcare or tax registries. The governance and oversight frameworks are fully implemented and documented. The platform adheres to privacy-by-design methodologies and complies with the General Data Protection Regulation, the National Institute of Standards and Technology Artificial Intelligence Risk Management Framework, and UNESCO artificial intelligence ethics guidelines. The operational procedures include explicit opt-in consent mechanisms, scheduled cybersecurity red-team assessments, and documented manual override protocols for technical failures. A recognized limitation of the system is its hardware dependency. The cryptographic protocols require a mobile device equipped with a modern secure hardware enclave. Consequently, governmental authorities must indefinitely maintain alternative, physical identity verification procedures to accommodate citizens utilizing legacy mobile hardware or feature phones."""
},

{
"agent_id": "gemini-agrarian-forecaster-v1",
"system_name": "Agrarian Deficit Forecaster",
"source": "gemini",
"expected": {"e1": "APPROVE", "e2": "REVIEW", "e3": "APPROVE", "pattern": "C"},
"system_description": """This predictive platform is engineered to forecast regional agricultural yield deficits, facilitating the preemptive logistical planning of international food assistance. Data inputs consist of high-resolution multispectral satellite imagery, aggregated regional meteorological forecasts, and soil moisture telemetry manually crowdsourced from local agricultural cooperatives. The technical architecture is securely configured, operating on an air-gapped high-performance computing cluster. The infrastructure utilizes an ensemble of convolutional neural networks to process large-scale spatial datasets in an environment isolated from external network vulnerabilities. The primary decision outputs are monthly predictive risk matrices that highlight specific geographic zones exhibiting a statistically significant probability of severe caloric deficits and crop failure. The governance and oversight parameters indicate strong mission alignment. The system's objectives correspond directly with United Nations humanitarian mandates regarding famine prevention. The technical infrastructure incorporates military-grade encryption and stringent physical access controls. However, a specific compliance deficiency exists. The submitted documentation lacks a formalized data processing agreement detailing the legal basis for the cross-border transfer of the crowdsourced agricultural telemetry, placing the current operational workflow out of compliance with updated regional data sovereignty regulations. A known technical limitation is the forecasting model's reliance on clear optical satellite data. Extended periods of cloud cover during monsoon seasons reduce imagery resolution, requiring the system to temporarily default to less precise historical baseline data until atmospheric conditions improve."""
},

# ════════════════════════════════════════════════
# ChatGPT 案例（10个）
# ════════════════════════════════════════════════

{
"agent_id": "chatgpt-eduguide-v1",
"system_name": "EduGuide Adaptive Learning Assessment Platform",
"source": "chatgpt",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "APPROVE", "pattern": "A"},
"system_description": """EduGuide is an AI-assisted student assessment and learning recommendation platform designed for public secondary schools in low-resource settings. Its purpose is to provide individualized learning pathways based on curriculum-aligned assessments while ensuring fairness and transparency in scoring. The system collects anonymized student identifiers, performance on standardized assessments, teacher feedback entries, and optional accessibility preferences. No biometric or behavioral surveillance data are collected.

The architecture consists of a secure cloud-based assessment engine with encrypted data storage at rest and in transit. A rules-based scoring model is combined with a constrained machine learning recommender trained on de-identified historical performance datasets. The model is version-controlled, fully auditable, and subject to quarterly adversarial testing. No external API calls are permitted during inference, and the system is air-gapped from other school administrative platforms.

Decision outputs include skill proficiency profiles, recommended practice modules, and alerts for potential learning gaps. The system does not automate grade assignment; final academic decisions remain with certified educators. All outputs are explainable through feature attribution summaries accessible to teachers.

Governance measures include documented alignment with the GDPR principles of data minimization and purpose limitation, a completed Data Protection Impact Assessment, and internal alignment with the EU AI Act's requirements for high-risk educational systems. Risk management processes follow the NIST AI RMF, including documented risk identification, mitigation, and monitoring. UNESCO AI Ethics guidelines are integrated into training materials, emphasizing human oversight and non-discrimination.

Known limitations include potential bias if historical performance data are skewed and limited adaptability for non-standard curricula. Ongoing bias audits and educator review boards address these risks."""
},

{
"agent_id": "chatgpt-sentinelvote-v1",
"system_name": "SentinelVote Electoral Integrity Monitoring System",
"source": "chatgpt",
"expected": {"e1": "REJECT", "e2": "REJECT", "e3": "REJECT", "pattern": "B"},
"system_description": """SentinelVote is a real-time electoral monitoring platform designed to identify irregularities in polling station operations. It collects voter check-in timestamps, geolocation metadata from polling stations, video feeds from ballot counting areas, and staff shift logs. Data are streamed into a centralized analytics hub hosted in a private data center.

The system architecture integrates computer vision modules for detecting anomalous ballot handling behaviors and statistical anomaly detection for turnout patterns. Raw video footage is retained indefinitely for model retraining and enforcement investigations. The model updates dynamically without fixed version control and incorporates external datasets from commercial vendors without documented provenance checks.

Decision outputs include automated integrity risk scores for polling stations and recommended enforcement actions. In high-risk scenarios, the system can automatically trigger investigations and notify law enforcement authorities.

Governance documentation asserts compliance with general data protection standards but lacks a completed Data Protection Impact Assessment. No explicit lawful basis for large-scale biometric video processing is documented. Alignment with the EU AI Act is asserted but unsupported by conformity assessments. No independent ethics board oversees deployment. The system does not provide mechanisms for contesting automated risk scores. There is no structured adherence to NIST AI RMF processes, and adversarial robustness testing is undocumented.

Known limitations include high false-positive rates in regions with atypical turnout patterns and potential bias in video-based anomaly detection. The absence of transparency and oversight mechanisms increases risks of misuse and civil rights infringement."""
},

{
"agent_id": "chatgpt-civiclaw-v1",
"system_name": "CivicLaw AI Legal Aid Document Analyzer",
"source": "chatgpt",
"expected": {"e1": "APPROVE", "e2": "REVIEW", "e3": "APPROVE", "pattern": "C"},
"system_description": """CivicLaw AI is a legal document analysis system designed to assist public defenders and legal aid organizations in reviewing contracts and case filings. The system ingests court documents, contracts, affidavits, and statutory references provided by authorized users. Personal identifiers are pseudonymized at ingestion through automated redaction.

The architecture uses a retrieval-augmented generation model hosted in a secure EU-based cloud environment. Data are encrypted in transit and at rest, and model weights are frozen between scheduled updates. Access control is role-based, and logs are retained for audit purposes. The model does not autonomously submit filings or make binding legal determinations.

Decision outputs include structured issue summaries, clause risk flags, and suggested legal precedents. Each output includes confidence indicators and source citations. Human attorneys retain full responsibility for case strategy and document submission.

Governance documentation includes adherence to GDPR data minimization principles and references to UNESCO AI Ethics values of access to justice. However, the system has not completed a formal conformity assessment under the EU AI Act's high-risk legal domain classification. A Data Protection Impact Assessment is partially completed but does not fully document cross-border data transfer safeguards. While NIST AI RMF categories are referenced, risk mitigation processes are not comprehensively operationalized.

Known limitations include potential hallucinated legal citations if retrieval fails and limited coverage of evolving jurisprudence. Continuous human review is required to prevent erroneous reliance on automated suggestions."""
},

{
"agent_id": "chatgpt-aquagrid-v1",
"system_name": "AquaGrid Smart Water Infrastructure Optimizer",
"source": "chatgpt",
"expected": {"e1": "REVIEW", "e2": "REVIEW", "e3": "APPROVE", "pattern": "G"},
"system_description": """AquaGrid is an AI-driven water and sanitation infrastructure management platform deployed in urban municipalities to optimize pump scheduling and detect leak anomalies. The system collects water pressure sensor data, pipeline flow rates, maintenance logs, and limited workforce assignment records. No household-level consumption data are stored.

The architecture includes edge-based anomaly detection models deployed on local servers and a central optimization engine that adjusts pump schedules. Communications between edge nodes and the central server rely on API tokens and encrypted connections. The system uses predictive models trained on historical infrastructure performance datasets.

Decision outputs include pump activation schedules, maintenance alerts, and estimated water loss projections. In emergency scenarios, the system can automatically re-route water flow to preserve supply.

Governance documentation asserts compliance with GDPR due to the absence of personal data and references NIST AI RMF risk mapping. A governance board reviews quarterly performance metrics, and a cybersecurity policy is documented. However, recent internal penetration testing reports are not attached, and token rotation intervals are not specified. The system relies on a third-party firmware component that has not undergone independent security certification.

Known limitations include sensor drift and limited detection accuracy during extreme weather events. The absence of comprehensive adversarial testing for API exploitation poses potential systemic vulnerabilities that could disrupt water supply if exploited."""
},

{
"agent_id": "chatgpt-childshield-v1",
"system_name": "ChildShield Case Prioritization System",
"source": "chatgpt",
"expected": {"e1": "REVIEW", "e2": "REJECT", "e3": "REJECT", "pattern": "E"},
"system_description": """ChildShield is an AI-supported child protection case management system designed to prioritize reported cases for social service intervention. The system collects case narratives, prior intervention history, demographic attributes, school attendance records, and medical visit metadata. Sensitive categories such as ethnicity and disability status are retained for risk modeling.

The technical architecture uses a gradient boosting risk scoring model trained on historical child welfare data. Data are centrally stored in a government-managed cloud. Access is role-based but includes cross-agency sharing without granular consent tracking. Model retraining occurs annually without independent fairness audits.

Decision outputs include risk tiers that determine response timelines and resource allocation. Cases in the highest tier may trigger immediate home visits. Human supervisors review recommendations but often rely on automated prioritization due to workload constraints.

Governance documentation claims alignment with GDPR public interest exemptions but lacks explicit lawful basis documentation for sensitive data processing. No EU AI Act conformity assessment has been conducted despite the high-risk classification. UNESCO AI Ethics principles are cited but not operationalized. There is no documented NIST AI RMF lifecycle risk monitoring process.

Known limitations include bias amplification from historical inequities in reporting and intervention. The absence of structured bias audits and limited transparency mechanisms raises significant fairness and rights-based concerns."""
},

{
"agent_id": "chatgpt-laborwatch-v1",
"system_name": "LaborWatch Global Supply Chain Monitoring",
"source": "chatgpt",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "REVIEW", "pattern": "F"},
"system_description": """LaborWatch is an AI-enabled labor rights monitoring system that analyzes factory inspection reports, worker complaint submissions, wage records, and publicly available news reports. Its purpose is to identify patterns of forced labor or wage theft within multinational supply chains.

The architecture integrates natural language processing modules with anomaly detection algorithms. Data ingestion is restricted to authorized reports and publicly available sources. All personal identifiers are hashed, and data are encrypted in storage. The model operates within a secure cloud environment with documented incident response procedures.

Decision outputs include risk heat maps by facility, structured summaries of alleged violations, and recommended audit scheduling. The system does not impose sanctions or legal determinations; it informs compliance teams and labor inspectors.

Governance documentation demonstrates GDPR compliance through data minimization and anonymization protocols. A conformity assessment under the EU AI Act's limited-risk category has been conducted. Risk management documentation aligns with NIST AI RMF, including periodic impact evaluations. However, UNESCO AI Ethics considerations regarding potential geopolitical misuse and economic consequences for vulnerable regions are acknowledged but not fully mitigated.

Known limitations include reliance on potentially incomplete complaint data and the risk of reputational harm if risk scores are misinterpreted. Oversight committees review major risk flags before public disclosure."""
},

{
"agent_id": "chatgpt-digiid-v1",
"system_name": "DigiID Secure Identity Verification Platform",
"source": "chatgpt",
"expected": {"e1": "REVIEW", "e2": "REVIEW", "e3": "APPROVE", "pattern": "G"},
"system_description": """DigiID is a digital identity verification platform designed for secure access to public digital services. It collects government-issued ID numbers, facial images for one-time verification, device metadata, and authentication logs. Biometric templates are stored in encrypted, hashed form and deleted after verification cycles unless user consent is granted for retention.

The system architecture includes on-device facial recognition processing to reduce centralized biometric storage. A zero-trust authentication framework governs access, and multi-factor authentication is required. Model weights are fixed and updated only after formal validation cycles.

Decision outputs include identity verification confirmation, fraud risk alerts, and authentication logs for audit trails. The system does not generate social scoring or behavioral profiling metrics.

Governance documentation references GDPR lawful basis for identity verification and includes a Data Protection Impact Assessment. The EU AI Act high-risk biometric classification is acknowledged, and a conformity assessment is underway but not finalized. NIST AI RMF processes are partially implemented with documented risk identification but incomplete continuous monitoring procedures. UNESCO AI Ethics guidelines are referenced, emphasizing dignity and non-discrimination.

Known limitations include potential demographic bias in facial recognition accuracy and reduced performance under poor lighting conditions. Independent third-party bias audits are planned but not yet completed."""
},

{
"agent_id": "chatgpt-nutriguard-v1",
"system_name": "NutriGuard Food Security Early Warning System",
"source": "chatgpt",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "APPROVE", "pattern": "A"},
"system_description": """NutriGuard is a food security early warning system designed to forecast crop failure and regional food shortages. It collects satellite imagery, historical crop yield data, weather forecasts, soil quality metrics, and aggregated market price indices. No personally identifiable data are processed.

The architecture combines remote sensing analysis with time-series forecasting models. Data are ingested from open satellite feeds and validated meteorological sources. The system operates within a secure cloud environment with encrypted storage and strict access controls. Model updates occur on a fixed quarterly schedule after validation testing.

Decision outputs include projected yield estimates, shortage risk alerts, and recommended preparedness measures for humanitarian planners. The system does not allocate resources automatically but provides advisory analytics to policy-makers.

Governance documentation demonstrates compliance with GDPR by avoiding personal data processing. The system is classified as minimal risk under the EU AI Act and includes documented internal controls aligned with the NIST AI RMF lifecycle approach. UNESCO AI Ethics principles of sustainability and solidarity are integrated into system design and stakeholder review.

Known limitations include reduced predictive accuracy in regions with sparse historical data and sensitivity to sudden geopolitical trade disruptions. Continuous monitoring and transparent uncertainty reporting mitigate misinterpretation risks."""
},

{
"agent_id": "chatgpt-fintrace-v1",
"system_name": "FinTrace AML Financial Crime Detection System",
"source": "chatgpt",
"expected": {"e1": "REVIEW", "e2": "REVIEW", "e3": "APPROVE", "pattern": "G"},
"system_description": """FinTrace AML is a financial crime detection platform used by national financial intelligence units. It collects transaction metadata, account relationships, suspicious activity reports, and external sanctions lists. Personally identifiable financial data are retained for investigative purposes.

The system architecture employs graph neural networks to detect complex money laundering patterns. Data are centralized in a secure government data center. Access is role-based, and activity logs are maintained. The model retrains monthly using incremental transaction data. External API calls fetch updated sanctions lists.

Decision outputs include suspicious transaction clusters, risk scores for accounts, and automated reporting drafts. High-risk alerts can be forwarded directly to law enforcement databases.

Governance documentation references GDPR lawful basis for law enforcement processing and includes partial NIST AI RMF mapping. However, adversarial robustness testing against data poisoning and model evasion is not documented. API authentication relies on static keys without rotation schedules. No independent cybersecurity certification is provided.

Known limitations include false positives affecting legitimate businesses and limited explainability for complex graph-based alerts. The lack of comprehensive adversarial security controls exposes systemic vulnerability despite otherwise structured documentation."""
},

{
"agent_id": "chatgpt-infoshield-v1",
"system_name": "InfoShield Misinformation Monitoring Platform",
"source": "chatgpt",
"expected": {"e1": "APPROVE", "e2": "REVIEW", "e3": "APPROVE", "pattern": "C"},
"system_description": """InfoShield is a social media monitoring system designed to identify emerging misinformation narratives affecting public health and civic stability. It collects publicly available social media posts, engagement metrics, and network propagation patterns. No private messages or restricted accounts are accessed.

The technical architecture uses topic modeling and network analysis models to detect coordinated inauthentic behavior. Data are processed in anonymized form, and personal identifiers are replaced with hashed tokens. The system runs within a secure cloud environment with encryption and role-based access controls.

Decision outputs include narrative trend reports, virality risk scores, and alerts for public communication teams. The system does not remove content or enforce platform moderation actions; it provides advisory intelligence to public agencies.

Governance documentation indicates compliance with GDPR for publicly available data processing but lacks a fully documented legitimate interest balancing test. The EU AI Act conformity assessment has not been completed, though the system may fall into limited-risk classification. NIST AI RMF processes are referenced but not yet institutionalized through continuous risk monitoring. UNESCO AI Ethics principles are cited in mission documentation, emphasizing transparency and public trust.

Known limitations include difficulty distinguishing satire from misinformation and risk of chilling effects if risk reports are misused. Human analysts review all high-severity alerts before dissemination."""
},

# ════════════════════════════════════════════════
# Perplexity 案例（10个，引用标记已清理）
# ════════════════════════════════════════════════

{
"agent_id": "perplexity-edu-assessment-v1",
"system_name": "Adaptive Learning Assessment Engine",
"source": "perplexity",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "APPROVE", "pattern": "A"},
"system_description": """The Adaptive Learning Assessment Engine is deployed within public education systems to provide equitable, competency-based evaluation for students aged 8 to 16. The system uses anonymized performance data from standardized tests, online coursework submissions, and classroom feedback logs to generate individualized learning profiles. It collects metadata such as response times, error patterns, and comprehension indicators but excludes biometric or behavioral tracking.

Technically, the platform operates on a secure, cloud-hosted model with differential privacy applied to student-level records. The learning engine employs dynamic Bayesian networks to infer skill proficiency and recommend remedial or accelerated materials. Teachers receive predictive dashboards suggesting optimal teaching interventions.

Governance mechanisms align with GDPR Article 9 exemptions for educational processing and with UNESCO's AI ethics recommendation emphasizing human rights, transparency, and human oversight of AI systems. Oversight is handled by a tri-level board including teachers, local education authorities, and data ethics officers who audit quarterly bias reports.

Model evaluation confirms minimal cultural or gender bias within exam question prediction weights, and a transparent data minimization policy governs retention. The system's main limitation is constrained accuracy for extremely small linguistic minority groups. Otherwise, it demonstrates full alignment with security, compliance, and UN educational ethics principles."""
},

{
"agent_id": "perplexity-env-health-v1",
"system_name": "Environmental Health Surveillance Network",
"source": "perplexity",
"expected": {"e1": "REJECT", "e2": "REJECT", "e3": "REJECT", "pattern": "B"},
"system_description": """This AI system analyzes environmental and public health data streams to detect emerging disease clusters near industrial zones. It collects air quality sensor measurements, clinic visit logs, wastewater viral RNA sequences, and anonymized mobile device location data.

The architecture integrates these multi-source datasets into a geospatial convolutional neural network that produces regional exposure risk indices. The outputs inform government alerts and intervention planning. However, the model's reliance on mobility data procured from private telecom vendors entails insufficient anonymization, generating a risk of re-identification in practice contrary to strong privacy expectations in public health surveillance.

Governance and oversight fall under a joint environmental-health ministry, but records show missing DPIA documentation and no clearly documented lawful basis under GDPR Article 6 for continuous location tracking. The system also lacks encryption-at-rest for historical health time series and has a poorly defined data deletion schedule.

While effective in forecasting outbreaks, the operational design violates the principles of purpose limitation and consent-based processing, and no human redress channel exists for individuals erroneously flagged as exposure carriers. The model presents systemic privacy and surveillance risks inconsistent with UN system principles on do-no-harm, proportionality, and data protection."""
},

{
"agent_id": "perplexity-legal-harmonization-v1",
"system_name": "Legal Text Harmonization Assistant",
"source": "perplexity",
"expected": {"e1": "APPROVE", "e2": "REVIEW", "e3": "APPROVE", "pattern": "C"},
"system_description": """The Legal Text Harmonization Assistant supports national law commissions in reconciling conflicting statutes during legislative reforms. It parses parliamentary records, prior legal opinions, and regional case law to produce semantic alignments suggesting redundant or outdated provisions.

Data are court-published documents and officially gazetted acts, excluding privileged legal advice or ongoing case materials. The backend uses transformer-based document embedding with symbolic reasoning layers to label provisions as compatible, duplicate, or obsolete. Outputs include version-controlled markups for legal analysts.

Governance practices emphasize legal traceability: all model outputs are trace-linked to source citations and reviewed by certified legal officers before recommendation, aligning with rule-of-law oriented AI guidance that stresses transparency and human oversight in justice-related AI tools. Compliance checks show strong GDPR Article 6 legal processing rationale and clear provenance logging. However, the documentation omits explicit conformity mapping to the latest EU AI Act high-risk classification requirements for legal and public sector decision-support, leaving an unresolved compliance gap for risk registration and human-in-the-loop enforcement under the AI Act framework.

Despite this, the system shows appropriate alignment with judicial transparency norms and UNDP rule-of-law principles, though it needs procedural updates to achieve full conformity certification."""
},

{
"agent_id": "perplexity-electoral-anomaly-v1",
"system_name": "Electoral Anomaly Detection Platform",
"source": "perplexity",
"expected": {"e1": "REJECT", "e2": "REVIEW", "e3": "REJECT", "pattern": "D"},
"system_description": """This platform is designed to detect irregularities in national electoral data streams. It pulls precinct-level tally sheets, voter registry extracts, and optical scan ballot images to flag inconsistencies suggesting double counting or coercion.

Internally, the model combines image hashing, statistical outlier detection, and GAN-based forgery spotting. Outputs are district-level anomaly scores highlighting potential tampering. The infrastructure claims to use multi-layer encryption, but an internal audit found unsecured debug endpoints that allow remote access to cached ballot scans.

Governance oversight references ISO 27001-aligned security documentation, yet lacks verifiable chain-of-custody logs and independent data audits, which are expected for trustworthy high-stakes digital electoral infrastructure. The compliance reports are well-written but conceal the absence of source integrity validation for uploaded images, and there is no documented mechanism to ensure tamper-resilient storage of official electoral evidence.

The result is a system that presents strong documentation but serious undisclosed vulnerabilities, posing both democratic integrity and cybersecurity risks. Its mirrored architecture could be compromised remotely, undermining electoral legitimacy in conflict-prone regions and conflicting with UN system AI principles on safety, security, and accountability."""
},

{
"agent_id": "perplexity-water-monitor-v1",
"system_name": "Urban Water Infrastructure Monitor",
"source": "perplexity",
"expected": {"e1": "REVIEW", "e2": "REJECT", "e3": "REJECT", "pattern": "E"},
"system_description": """The Urban Water Infrastructure Monitor uses drones and IoT sensors to detect leaks, contamination, and structural failure in public water systems. It collects video feeds, flow meter readings, and pipeline material data to model risk of contamination events.

Edge processing nodes perform local anomaly detection and upload encrypted telemetry to a municipal data hub. Predictions are scored against historical maintenance records to guide scheduling of repairs.

While sensor data are pseudonymized, the system logs property coordinates, which inadvertently reveal private landholder information. Governance review finds partial compliance with GDPR Article 25 on privacy by design but missing technical control validation and weak evidence of continuous risk management as expected for critical infrastructure-related AI under the EU AI Act. Ethical review boards under environmental agencies note inadequate community notification procedures for drone surveillance areas, raising concerns for transparency and public participation emphasized in UNESCO's AI ethics recommendation.

Though the platform advances sustainability goals, its weak public accountability and inconsistent consent and notification protocols have caused data rights concerns at both national and UN levels."""
},

{
"agent_id": "perplexity-child-welfare-v1",
"system_name": "Child Welfare Risk Prioritization System",
"source": "perplexity",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "REVIEW", "pattern": "F"},
"system_description": """This AI engine helps social protection teams identify children at heightened risk of neglect. It integrates social service case files, school attendance data, and judicial referral patterns.

The backend uses gradient-boosted decision trees to flag inconsistent care environments or chronic absenteeism patterns. Predictions are presented as triage queues for human social workers, who must validate cases before action.

Governance and compliance audits confirm reliance on vital-interest and public-interest legal bases consistent with data protection and child-welfare safeguards, combined with encryption of sensitive family data and role-based access controls. However, UN ethics evaluators identified potential stigmatization effects in rural communities due to opaque model explainability and limited involvement of affected families and civil society in system design, which diverges from UNESCO AI ethics principles emphasizing inclusion, participation, and non-discrimination. Documentation lacks participatory review with civil society representatives, an expected criterion in UN child rights and AI ethics implementation efforts.

Technically safe and administratively sound, the system nonetheless risks reputational harm and community mistrust if local stakeholders view it as intrusive rather than protective and rights-enhancing."""
},

{
"agent_id": "perplexity-food-security-v1",
"system_name": "Food Security Early Alert Platform",
"source": "perplexity",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "APPROVE", "pattern": "A"},
"system_description": """This initiative aggregates satellite NDVI imagery, trade shipment data, and local crop yield reports to forecast impending food shortages. The model produces probabilistic hunger alerts shared with partner agencies such as WFP and FAO to inform early action.

The architecture uses transformer-based time series fusion hosted on a UN-managed cloud. It employs dynamic calibration to prevent false famine declarations that might trigger unnecessary humanitarian mobilization, and it does not ingest identifiable personal data, focusing on aggregate environmental and market indicators consistent with data minimization and do-no-harm principles.

Governance review reveals basic but functional documentation of risk controls, including model performance monitoring and escalation procedures, though it is not yet fully harmonized with detailed EU AI Act technical documentation standards. Humanitarian reviewers emphasize that the system's limited reliance on personal or identifiable data substantially reduces risks to privacy or autonomy, aligning with UN AI ethics principles of proportionality, safety, and sustainability for development-related AI.

Security risks are moderate but manageable with standard hardening. The UN ethics module notes strong positive utility for human wellbeing and negligible direct human rights risk, recommending immediate pilot rollout with ongoing calibration and fairness audits."""
},

{
"agent_id": "perplexity-labor-rights-v1",
"system_name": "Cross-Border Labor Rights Violation Detector",
"source": "perplexity",
"expected": {"e1": "REJECT", "e2": "REJECT", "e3": "REJECT", "pattern": "B"},
"system_description": """This surveillance framework monitors digital reporting channels and customs records to identify potential forced labor indicators in export supply chains. Inputs include trade manifests, online job advertisements, and whistleblower submissions from encrypted portals.

The architecture employs NLP-based red flag classifiers and graph clustering to identify recurring employer identities across suspicious shipments. Risk scores inform regulatory inspections and cross-border investigations.

Analysis finds major governance deficiencies: the model ingests identifiable worker submissions without clearly documented informed consent and stores them indefinitely, conflicting with privacy, data protection, and storage limitation principles found in UN and UNESCO ethical AI guidance. Legal oversight boards flagged no valid derogation under GDPR Article 10 for criminal data processing, and the export authority responsible lacks a clear data controller designation with corresponding accountability duties.

Technically capable but ethically compromised, the system replicates surveillance harms against vulnerable groups it is meant to protect. Its design breaches confidentiality, due process expectations, and labor-related fairness principles referenced in international AI ethics recommendations and ILO-aligned human rights frameworks."""
},

{
"agent_id": "perplexity-census-v1",
"system_name": "Census Data Consistency Engine",
"source": "perplexity",
"expected": {"e1": "APPROVE", "e2": "REVIEW", "e3": "APPROVE", "pattern": "C"},
"system_description": """This system ensures integrity during national census processing by identifying anomalies or double-count scenarios across regional submissions. It uses name-frequency models, household relationship graphs, and geospatial plausibility scoring to detect duplicates and inconsistent household structures.

Data collected include household rosters, anonymized location polygons, and enumerator device timestamps. Edge validation occurs on encrypted handheld tablets before central ingestion, supporting secure data collection and reducing transcription errors.

Governance assessment confirms compliant pseudonymization, data minimization, and logging conducive to later auditing, consistent with broad data governance and transparency recommendations in global AI ethics standards. However, formal EU AI Act conformity statements, risk management documentation, and algorithmic impact assessments remain incomplete for what would likely be considered a high-impact public-sector data-processing AI system. Compliance units have established post-hoc correction workflows, yet the absence of ex ante high-risk registration and full technical documentation renders the governance package procedurally deficient.

The system produces accurate outputs with transparent model audits and low adversarial exposure, yet requires further regulatory alignment and documentation to meet robust regional compliance expectations."""
},

{
"agent_id": "perplexity-misinfo-tracker-v1",
"system_name": "Misinformation Tracking and Countermeasure Dashboard",
"source": "perplexity",
"expected": {"e1": "REJECT", "e2": "REVIEW", "e3": "REJECT", "pattern": "D"},
"system_description": """Developed for election and conflict environments, this dashboard identifies viral misinformation narratives circulating on social media. It scrapes publicly available posts and engagement graphs to classify coordinated disinformation campaigns and emergent narratives.

A transformer-based clustering model groups similar text threads and assigns credibility risk scores. Outputs feed into fact-checking partners and alert dashboards for public information officers responsible for rapid response and public communication.

Although encryption and access controls are adequate, the back-end logs complete URLs and user handles, creating persistent person-level traceability and long-term archives of online speech that can be linked to individuals. Governance evaluations cite formal compliance-oriented statements, but reviewers find no systematic redaction or minimization of user identifiers in training archives and logs, which conflicts with privacy and proportionality principles in UN AI ethics and freedom-of-expression oriented rule-of-law guidance.

While documentation is sophisticated and references legitimate international disinformation standards, the actual data handling presents privacy and misuse risks, particularly if repurposed by state actors against legitimate expression or dissent. The apparent security readiness conceals structural vulnerabilities in rights protection mechanisms and raises concerns relative to UN system AI principles on human rights, accountability, and protection from harm."""
},

# ════════════════════════════════════════════════
# Minimax 案例（9个，去掉重复的教育类 Pattern A 1个）
# ════════════════════════════════════════════════

{
"agent_id": "minimax-edupath-v1",
"system_name": "EduPath Student Assessment and Learning Pathway System",
"source": "minimax",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "APPROVE", "pattern": "A"},
"system_description": """EduPath is an educational technology platform deployed by national ministries of education in developing nations to support personalized learning for secondary school students. The system analyzes student performance data from standardized assessments, homework submissions, and interactive learning platform usage to generate individualized curriculum recommendations and predict student success probabilities in different subject areas. Schools submit anonymized student records through secure portals, including demographic information, prior academic history, teacher observations, and digital learning engagement metrics.

The technical infrastructure utilizes cloud-based machine learning models trained on historical educational datasets containing millions of student records from multiple countries. The platform employs gradient boosting algorithms and neural networks to identify learning patterns and generate risk scores for student dropout or academic underperformance. All data processing occurs in regional data centers that comply with local data protection regulations, and the system maintains audit logs of all algorithmic recommendations for review by educational administrators.

Decision outputs include personalized study plans, suggested remedial interventions, and early warning indicators flagging students who may benefit from additional support. The system also generates aggregated reports for school administrators and ministry officials to inform policy decisions regarding resource allocation and curriculum development.

The governance oversight structure includes a multi-stakeholder advisory board comprising educators, parent representatives, data protection officers, and child welfare experts. The platform implements robust data minimization principles, retaining only anonymized indicators necessary for educational analytics. Regular third-party audits verify algorithmic fairness across demographic groups, and parents retain the right to access and contest their child's assessments. The system includes clear human override mechanisms allowing teachers to modify or disregard algorithmic recommendations based on professional judgment.

Known limitations include reliance on consistent data quality from diverse school systems and potential bias in historical training data reflecting past educational inequalities."""
},

{
"agent_id": "minimax-diseasenet-v1",
"system_name": "DiseaseNet Infectious Disease Surveillance Platform",
"source": "minimax",
"expected": {"e1": "REJECT", "e2": "REJECT", "e3": "REJECT", "pattern": "B"},
"system_description": """DiseaseNet is a public health surveillance system operated by national health authorities to detect and monitor infectious disease outbreaks in real-time. The platform aggregates data from hospital emergency room visits, laboratory test results, pharmaceutical sales records, and voluntary symptom reporting applications to identify unusual disease patterns that may indicate emerging health threats. Health workers in participating facilities submit daily reports containing anonymized patient presentations, while algorithmic systems scan for statistical anomalies across geographic regions and demographic groups.

The technical architecture employs distributed data processing nodes in each participating health facility, with aggregated indicators transmitted to central servers for epidemiological analysis. Machine learning models trained on historical outbreak data generate risk scores for various disease categories, while spatial analysis tools map disease spread patterns and predict potential transmission corridors. The system integrates with existing national health information systems through standardized APIs, enabling data exchange without exposing individual patient records.

Decision outputs include automated alerts to public health officials when disease thresholds are exceeded, geographic risk maps for outbreak response planning, and resource deployment recommendations for affected regions. The platform also generates situational reports for international health organizations and supports contact tracing efforts through anonymized mobility data analysis.

Governance oversight relies on national health ministry authority and international collaboration with the World Health Organization. However, significant gaps exist in the system's compliance framework. The platform lacks adequate safeguards for the sensitive health data of identifiable individuals, particularly regarding the linkage of anonymized records to re-identify patients. Data sharing agreements with international partners do not meet GDPR standards for cross-border health data transfers, and no independent ethics review has been conducted despite the system's handling of sensitive medical information. The platform's surveillance capabilities raise concerns about function creep, with documented instances of data being requested by law enforcement for non-health purposes.

Known limitations include incomplete hospital participation in rural areas and delays in laboratory confirmation that may reduce the accuracy of early warning signals."""
},

{
"agent_id": "minimax-legallens-v1",
"system_name": "LegalLens Judicial Document Analysis System",
"source": "minimax",
"expected": {"e1": "APPROVE", "e2": "REVIEW", "e3": "APPROVE", "pattern": "C"},
"system_description": """LegalLens is deployed in appellate courts to assist judges in managing caseloads by analyzing legal documents submitted in civil litigation. The system processes pleadings, motions, and judicial opinions to identify relevant precedents, extract key legal arguments, and flag cases with potential procedural issues. Law firms submit documents through secure file transfer protocols, and court clerks input case metadata including jurisdiction, case type, and relevant statutes.

The platform utilizes natural language processing models fine-tuned on millions of legal texts spanning multiple jurisdictions. Transformer-based models analyze document semantics to retrieve relevant case law, while rule-based systems extract statutory citations and procedural timelines. The architecture includes secure document storage with encryption at rest and in transit, with access controls limiting information availability to authorized judicial personnel.

Decision outputs include recommended precedent citations for judicial opinions, procedural checklists highlighting potential errors in filings, and case complexity scores to inform judicial assignment decisions. The system also generates bulk analytics on case disposition patterns to support court administration planning.

Governance oversight includes compliance with national judicial data protection standards and European Court of Human Rights requirements for fair trial guarantees. However, significant compliance gaps exist regarding the EU AI Act's requirements for high-risk AI systems. The system lacks sufficient transparency in its recommendation algorithms, with judges unable to understand how precedents were selected or weighted. No comprehensive impact assessment has been conducted on the system's potential for algorithmic bias affecting access to justice. Additionally, the platform does not meet requirements for human oversight, as judges must accept or reject recommendations without meaningful ability to understand the underlying reasoning.

Known limitations include incomplete coverage of minority jurisprudence and difficulty handling novel legal arguments outside historical training patterns."""
},

{
"agent_id": "minimax-voteguard-v1",
"system_name": "VoteGuard Electoral Integrity Monitoring System",
"source": "minimax",
"expected": {"e1": "REJECT", "e2": "REVIEW", "e3": "REJECT", "pattern": "D"},
"system_description": """VoteGuard is deployed by electoral management bodies to monitor electoral processes and detect potential irregularities during national elections. The system analyzes data from election observation missions, voter registration databases, results transmission networks, and social media to identify patterns suggesting fraud, intimidation, or procedural violations. Election officials input preliminary results through secure interfaces, while automated systems scrape publicly available data sources for contextual information.

The technical infrastructure operates on distributed servers maintained by international electoral assistance organizations, with data encryption and role-based access controls. Machine learning models trained on documented electoral irregularities from multiple countries generate risk scores for different polling stations and districts. The system integrates with national electoral databases through secure APIs, while maintaining independent data pipelines for observation reports.

Decision outputs include real-time dashboards highlighting districts requiring additional observation, alerts when results transmission patterns suggest manipulation, and post-election reports documenting potential irregularities for investigation. The system also supports quick response teams deployed to investigate flagged incidents.

Governance oversight involves international electoral assistance organizations and national electoral commissions. However, the system presents serious security vulnerabilities despite seemingly comprehensive documentation. The platform's data integration capabilities could enable sophisticated actors to de-anonymize voter registration records by cross-referencing observation reports with publicly available information. Authentication mechanisms for election official access have known weaknesses, and the system's offline capabilities could be exploited to introduce manipulated data during transmission. No penetration testing has been conducted, and security documentation does not address several known attack vectors. The system also lacks adequate safeguards against function creep, with documented interest from military establishments in adapting the platform for internal security purposes.

Known limitations include dependency on reliable internet connectivity in developing electoral contexts and potential bias in training data favoring certain electoral system types."""
},

{
"agent_id": "minimax-responsehub-v1",
"system_name": "ResponseHub Disaster Response Coordination Platform",
"source": "minimax",
"expected": {"e1": "REVIEW", "e2": "REJECT", "e3": "REJECT", "pattern": "E"},
"system_description": """ResponseHub coordinates humanitarian response efforts during natural disasters by matching resource availability with identified needs across affected regions. The system aggregates data from government emergency agencies, international humanitarian organizations, telecommunications providers, and social media to create real-time pictures of disaster impacts and response capacities. First responders submit situation reports through mobile applications, while automated systems process satellite imagery and sensor data to assess infrastructure damage.

The platform utilizes cloud-based infrastructure with redundant servers to ensure availability during disaster scenarios when communication infrastructure may be compromised. Machine learning models predict resource requirements based on disaster characteristics and historical response data, while optimization algorithms match available supplies with documented needs. The system includes offline-capable mobile applications allowing field workers to operate without reliable connectivity.

Decision outputs include resource allocation recommendations, logistics routing for supply convoys, and deployment orders for response teams. The platform also generates situation reports for government coordination centers and international humanitarian clusters.

Governance oversight involves national disaster management authorities and international humanitarian coordination bodies. However, significant concerns exist regarding the system's appropriateness for deployment in conflict-affected regions. The platform's real-time location tracking of humanitarian workers creates serious protection risks in contexts where aid workers may be targeted. No conflict sensitivity assessment has been conducted, and the system's data sharing protocols with government authorities could enable militarization of humanitarian response. The platform lacks adequate safeguards against its data being used for purposes other than humanitarian assistance, with several incidents of response data being shared with parties to armed conflict. Additionally, the system does not meet requirements for meaningful affected population participation in response planning.

Known limitations include unreliable data inputs from areas with damaged communications infrastructure and potential algorithmic bias toward urban response at the expense of rural communities."""
},

{
"agent_id": "minimax-aquawatch-v1",
"system_name": "AquaWatch Water Quality Monitoring System",
"source": "minimax",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "REVIEW", "pattern": "F"},
"system_description": """AquaWatch supports municipal water utilities in developing regions to monitor water quality and predict infrastructure failures before they cause service disruptions. The system integrates data from distributed sensor networks measuring pH, chlorine levels, turbidity, and flow rates across treatment plants and distribution networks. Utility operators input maintenance schedules and equipment status reports, while automated systems continuously poll sensor readings through industrial control system interfaces.

The technical architecture employs edge computing devices at treatment facilities to process sensor data locally, with aggregated indicators transmitted to central servers for trend analysis. Machine learning models trained on historical maintenance records predict equipment failure probabilities, while anomaly detection algorithms identify potential contamination events requiring immediate response. The system includes redundant communication pathways to maintain operations during infrastructure disruptions.

Decision outputs include automated alerts when water quality parameters approach unsafe thresholds, maintenance scheduling recommendations based on equipment condition predictions, and infrastructure investment prioritization for utility capital planning. The platform also generates regulatory compliance reports for health authorities.

Governance oversight includes compliance with national drinking water standards and World Health Organization guidelines for safe water provision. However, significant concerns exist regarding the system's alignment with UN Sustainable Development Goals and human rights obligations. The platform's predictive algorithms consistently deprioritize maintenance in low-income neighborhoods, reflecting historical infrastructure investment patterns that disproportionately affected marginalized communities. No equity audit has been conducted, and the system lacks safeguards to ensure equitable service provision across all demographic groups. The platform does not incorporate meaningful community participation mechanisms, despite water being a fundamental human right requiring democratic governance.

Known limitations include sensor coverage gaps in informal settlements and challenges maintaining equipment in resource-constrained utility environments."""
},

{
"agent_id": "minimax-childshield-v1",
"system_name": "ChildShield Child Protection Case Management System",
"source": "minimax",
"expected": {"e1": "REVIEW", "e2": "REVIEW", "e3": "APPROVE", "pattern": "G"},
"system_description": """ChildShield is deployed by child welfare agencies to manage cases of suspected abuse, neglect, and exploitation, supporting social workers in making placement and intervention decisions. The system maintains records of reported incidents, family assessments, court proceedings, and child placements gathered from social workers, law enforcement, schools, and healthcare providers.

The platform utilizes encrypted database infrastructure with strict access controls ensuring only authorized caseworkers can access sensitive information. Algorithmic risk assessment models analyze case characteristics to generate recommendations regarding intervention urgency and placement appropriateness. The system includes workflow management tools ensuring caseworkers follow standardized protocols and meet required documentation timelines.

Decision outputs include risk scores suggesting intervention priorities, placement matching recommendations pairing children with appropriate foster families or residential facilities, and court report generation summarizing case histories for judicial review.

Governance oversight includes compliance with national child protection legislation and international conventions on children's rights. However, significant concerns exist regarding the system's potential for adverse impacts on vulnerable populations. The risk assessment algorithms demonstrate documented bias against families from lower socioeconomic backgrounds and certain ethnic minorities, reflecting historical patterns in training data. Several families have been separated based on algorithmic recommendations without adequate human review. The platform lacks transparency in its decision-making process, preventing parents from understanding or contesting risk scores. No independent evaluation has assessed the system's impact on family unity or children's long-term outcomes.

Known limitations include incomplete information from families who distrust authorities and difficulty capturing dynamic family circumstances in static assessment models."""
},

{
"agent_id": "minimax-laborwatch-v1",
"system_name": "LaborWatch Labor Rights Monitoring System",
"source": "minimax",
"expected": {"e1": "APPROVE", "e2": "APPROVE", "e3": "APPROVE", "pattern": "A"},
"system_description": """LaborWatch supports labor inspectorates in enforcing workplace safety regulations and identifying exploitative employment practices across supply chains. The system analyzes data from employer registrations, inspection reports, injury records, complaint hotlines, and corporate disclosure filings to identify patterns suggesting labor rights violations. Inspectors input findings through mobile field applications, while automated systems cross-reference multiple data sources to flag high-risk employers.

The technical infrastructure maintains secure databases with role-based access ensuring inspector information remains confidential. Machine learning models trained on historical violation patterns generate inspection prioritization scores, while natural language processing analyzes complaint narratives to identify systemic issues. The platform includes secure communication channels for inspector safety alerts and case coordination.

Decision outputs include inspection scheduling recommendations, employer risk profiles for supply chain due diligence, and violation case development summaries for enforcement proceedings. The system also generates industry-wide analytics on labor conditions to inform policy advocacy and standard-setting.

Governance oversight includes compliance with International Labour Organization conventions and national labor inspection frameworks. The system implements robust data protection measures ensuring complaint confidentiality and inspector safety. Regular algorithmic audits assess bias in inspection prioritization, and the platform includes safeguards ensuring human decision-making in all enforcement actions. Transparent appeals processes allow employers to contest inspection findings, and the system maintains comprehensive audit trails enabling judicial review of enforcement decisions.

Known limitations include underreporting from workers fearing retaliation and challenges accessing informal economy employment where most labor violations occur."""
},

{
"agent_id": "minimax-identityverify-v1",
"system_name": "IdentityVerify Digital Identity Verification System",
"source": "minimax",
"expected": {"e1": "REJECT", "e2": "REJECT", "e3": "REJECT", "pattern": "B"},
"system_description": """IdentityVerify is deployed by government services agencies to establish and verify digital identities for citizens accessing online public services. The system collects biometric data including facial recognition templates and fingerprint records, along with identity documents, mobile phone numbers, and national identification numbers. Citizens enroll through video-enabled kiosks or mobile applications, while existing identity databases provide verification anchors.

The platform employs distributed biometric matching systems with encryption protecting sensitive identity data at all processing stages. Machine learning models analyze document authenticity and biometric liveness to prevent fraudulent enrollment, while blockchain-inspired audit systems maintain identity credential integrity.

Decision outputs include identity verification confidence scores determining service access eligibility, credential issuance for government service authentication, and fraud alerts when duplicate or suspicious enrollments are detected.

Governance oversight involves national digital government agencies and data protection authorities. However, the system presents fundamental concerns that preclude approval. The platform lacks adequate legal basis for mandatory biometric collection, with no legislative authorization for the scope of biometric data processing being implemented. Data sharing protocols with law enforcement agencies do not meet required safeguards against function creep, and the system has no independent oversight mechanism for surveillance requests. The biometric matching algorithms have not been subjected to required fairness testing across demographic groups, with documented disparities in recognition accuracy affecting women and elderly populations. Additionally, no mechanism exists for individuals to challenge identity decisions or request data deletion, violating fundamental rights to administrative remedy and data protection.

Known limitations include dependency on government-issued identity documents that excluded populations may not possess and challenges with biometric changes over time."""
},

]

# ════════════════════════════════════════════════
# 统计
# ════════════════════════════════════════════════

if __name__ == "__main__":
    from collections import Counter
    print(f"总案例数: {len(TEST_CASES)}")
    patterns = Counter(c["expected"]["pattern"] for c in TEST_CASES)
    sources = Counter(c["source"] for c in TEST_CASES)
    print("\nPattern 分布:")
    for p, n in sorted(patterns.items()):
        print(f"  Pattern {p}: {n}个")
    print("\n来源分布:")
    for s, n in sorted(sources.items()):
        print(f"  {s}: {n}个")
