/**
 * Convert DetailedEvaluation to Markdown for download.
 */
import type { DetailedEvaluation } from '../data/mockData'

export function evaluationToMarkdown(e: DetailedEvaluation): string {
  const date = new Date(e.submitted_at).toLocaleString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit',
  })

  const lines: string[] = []
  lines.push(`# UNICC AI Safety Council — Full Assessment Report`)
  lines.push('')
  lines.push(`## System Under Evaluation`)
  lines.push('')
  lines.push(`- **Name:** ${e.system_name}`)
  lines.push(`- **Agent ID:** ${e.agent_id}`)
  lines.push(`- **Category:** ${e.category}`)
  lines.push(`- **Submitted:** ${date}`)
  lines.push('')
  lines.push(`### Description`)
  lines.push('')
  lines.push(e.description)
  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push('## Part 1 — Expert Analyses')
  lines.push('')

  for (const r of e.expert_reports) {
    lines.push(`### ${r.icon} ${r.title}`)
    lines.push('')
    lines.push(`**Recommendation:** ${r.recommendation}  |  *${r.elapsed}s elapsed*`)
    lines.push('')
    lines.push(`#### Dimension Scores`)
    lines.push('')
    for (const s of r.scores) {
      const pct = Math.round((s.value / s.max) * 100)
      lines.push(`- ${s.label}: ${s.value}/${s.max} (${pct}%)`)
    }
    lines.push('')
    lines.push(`#### Key Findings (Evidence)`)
    lines.push('')
    for (const f of r.findings) {
      lines.push(`- ${f}`)
    }
    lines.push('')
    lines.push(`#### Regulatory References`)
    lines.push('')
    for (const ref of r.framework_refs) {
      lines.push(`- ${ref}`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push('## Part 2 — Council Debate')
  lines.push('')

  for (let i = 0; i < e.council_critiques.length; i++) {
    const c = e.council_critiques[i]
    lines.push(`### Critique ${i + 1}: ${c.from} → ${c.on}`)
    lines.push('')
    lines.push(`**${c.agrees ? 'Agrees' : 'Disagrees'}** | Divergence: ${c.divergence_type.replace(/_/g, ' ')}`)
    lines.push('')
    lines.push(`> "${c.key_point}"`)
    lines.push('')
    lines.push(`**Stance:** ${c.stance}`)
    lines.push('')
    lines.push(`**Evidence:**`)
    for (const ev of c.evidence) {
      lines.push(`- ${ev}`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push('## Part 3 — Expert Final Opinions')
  lines.push('')
  for (const r of e.expert_reports) {
    lines.push(`- **${r.shortTitle}:** ${r.recommendation}`)
  }
  lines.push('')

  lines.push('---')
  lines.push('')
  lines.push('## Part 4 — Arbitration Outcome')
  lines.push('')
  lines.push(`**Council Decision:** ${e.decision}`)
  lines.push('')
  lines.push(`### Rationale`)
  lines.push('')
  lines.push(e.final_rationale)
  lines.push('')

  if (e.key_conditions.length > 0) {
    lines.push(`### Required Actions`)
    lines.push('')
    for (let i = 0; i < e.key_conditions.length; i++) {
      lines.push(`${i + 1}. ${e.key_conditions[i]}`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push('*Generated by UNICC AI Safety Council. For official use only.*')
  return lines.join('\n')
}
